### ISSUE TITLE
Filter out keyspaces

### ISSUE THREAD

**Issue by nilroy** [sensu-plugins/sensu-plugins-cassandra#2]
The keyspace filter is not working as expected. I am running like this

  `./metrics-cassandra-graphite.rb --cfstats --filter <keyspace_name>`

But its showing output of all the keyspaces

Also in the comment header the name of the script is mentioned wrong as cassandra-metrics.rb whereas it should be metrics-cassandra-graphite.rb

**Comment by majormoses** [comment]
I would need to see your actual regex you gave an an output of the data to see what is going on.
