### ISSUE TITLE
key_cache related metrics is not captured with nodetool info command due to regex mismatch

### ISSUE THREAD

**Issue by tashiwangdi** [sensu-plugins/sensu-plugins-cassandra#7]
The regex :/^Key Cache[^:]+: size ([0-9]+) \(bytes\), capacity ([0-9]+) \(bytes\), ([0-9]+) hits, ([0-9]+) requests/     does not match the output from the nodetool info command which outputs as:

Key Cache              : entries 569669, size 100 MiB, capacity 100 MiB, 35689224 hits, 70654365 requests, 0.505 recent hit rate, 14400 save period in seconds

Cassandra version :  3.9.0

**Comment by jthunt** [comment]
I believe this can be closed now?  @tashiwangdi can you test?  Seems to be working for me.
